// 程序结构
program : (include)* (class | function | var | const)*

include : "include" literal               // 包含库文件，如：include "mathlib.mcdl"

// 注解系统
// 仅允许使用内置注解及插件注解
annotation : "@" ID | "@" ID "(" literal ("," literal)* ")"

// 类(单继承、单接口)
class : annotation* "class" ID ("(" identifier*")")? "{" (class_property | method)* "}"

class_property : type ID "?"?| "let" ID "?"? ("->" | ":") type

// 类型系统
type.2: ID array_dimension*
array_dimension: ("[" (ARRAY_SIZE | ID) "]") | "[]"

// type: ID ("[" (INT | ID) "]")*  // 允许变量

function : annotation* ("function"|"fn"|"def") ID params (("->" | ":") type)? (block|":")
         | annotation* ("function"|"fn")? type ID params (block|";")


method :annotation* "method" ID params (("->" | ":") type)? block
    | annotation* "method" type ID params block

params : "(" (param ("," param)*)? ")"

// 强制类型标注
param: "mut"? ID ("->" | ":") type ("=" expr)?
     | "mut"? type ID ("=" expr)?

// 代码块，包含多个语句
block : "{" statement* "}"
    | statement

// 流程控制
?statement : function
    | var                                                           // 变量声明
    | const                                                         // 常量声明
    | for_loop                                                      // for循环
    | while_loop                                                    // while循环
    | expr                                                          // 表达式
    | "free" identifier                             -> free_stmt    // 清理资源
    | "return" expr?                                -> return_stmt  // 返回
    | "if" "(" condition ")" block ("else" block)?  -> if_stmt      // 条件语句
    | "break"                                       -> break_stmt   // break语句
    | "continue"                                    -> continue_stmt// continue语句
    | "pass"                                        -> pass_stmt    // 空语句

for_loop : "for" "(" for_control ")" block        // 传统for循环
    | "for" "(" type ID ":" expr ")" block       // 增强for循环 (expr需为可迭代class)


while_loop : "while" "(" condition ")" block            // while循环

for_control : for_init? ";" condition? ";" for_update?


for_init: var | expr

condition: expr

for_update: expr

const: "const" ID (("->" | ":") type)? ("=" expr)  // 常量声明
     | "const" type ID ("=" expr)

// 变量声明
var: type "?"? ID ("=" expr)?
   | "let" ID "=" expr
   | ID ("->" | ":") type "?"? ("=" expr)?
   | "let" ID ("->" | ":") type "?"? ("=" expr)?


//| expr '?' '.' ID                                      -> SafeNavigation           // 安全导航
// 表达式
?expr : primary                                   // 基础表达式
    | FSTRING                                     -> fstring            // 插值字符串
    | "null"                                      -> null               // null句柄
    | expr "." ID arguments                       -> method_call        // 方法调用
    | expr "." ID                                 -> member_access      // 成员访问
    | expr "[" expr "]"                           -> array_access       // 数组访问
    | expr arguments                              -> function_call      // 函数调用
    | "-" expr                                    -> neg                // 负号
    | ("not"|"!") expr                            -> logical_not        // not运算符
    | expr ("*"|"/"|"%") expr                     -> factor             // 乘除模运算
    | expr ("+" | "-") expr                       -> term               // 加减运算
    | expr (">"|"<"|"=="|"!="|"<="|">=") expr     -> compare            // 比较运算
    | expr ("and"|"&&") expr                      -> logical_and        // and运算符
    | expr ("or"|"||") expr                       -> logical_or         // or运算符
    | expr "[" expr "]" "=" expr                  -> array_assignment   // 数组元素赋值
    | expr "." ID "=" expr                        -> member_assignment  // 成员属性访问
    | identifier "=" expr                         -> local_assignment   // 变量赋值


?primary : literal   // 字面量
    | identifier     // 标识符（变量、函数、类等）
    | paren          // 括号

// 标识符(不适用定义)
identifier: ID
paren: "(" expr ")"

// 辅助规则

arguments : ("(" (argument ("," argument)*)? ")")

// 当存在mut时代表传入量可变，目前仅对数组有效
argument : "mut"? expr

// 数字、普通字符串、布尔值、空值
literal : INT
    | FLOAT
    | STRING
    | "true" -> true
    | "false" -> false
    | array_literal

array_literal : "[" (literal ("," literal)*)? "]"

PYTHONIC_COMMENT: /#[^\n]*/
LUA_COMMENT: "[[" /(.|\n)*?/ "]]"

ARRAY_SIZE: /[1-9][0-9]*/     // 数组大小（正整数）
INT: /-?[0-9]+/               // 整数（可以为负）
FLOAT: /-?[0-9]+\.[0-9]+/     // 浮点数
FSTRING.3: /f"([^"\\]|\\.)*"/

%import common.ESCAPED_STRING -> STRING
%import common.CNAME -> ID
%import common.WS
%import common.CPP_COMMENT
%import common.C_COMMENT
%ignore WS
%ignore CPP_COMMENT
%ignore C_COMMENT
%ignore PYTHONIC_COMMENT
%ignore LUA_COMMENT